CC=i686-w64-mingw32-gcc
CFLAGS=-Wall -DWIN32 -O3
LDFLAGS=-L../lib/mingw32/lib
INCLUDE=-I../lib/mingw32/include
LIBS=-llibgd -lavutil -lavdevice -lavformat -lavcodec  -lswscale -lm

mtn: mtn.c 
	$(CC) -o ../bin/mtn.exe mtn.c $(CFLAGS) $(LDFLAGS) $(INCLUDE) $(LIBS)

clean:
	rm -f ../bin/mtn.exe
